import { jsPDF } from 'jspdf';

/**
 * PDF Export Utility
 * 
 * Generates PDF documents from opportunity data with consistent formatting.
 * Requirements: 17.1, 17.2, 17.3, 17.4
 */

/**
 * Generate PDF from opportunity data
 * 
 * @param {Object} opportunity - Opportunity object with all details
 * @returns {void} - Triggers browser download
 */
export const generateOpportunityPDF = (opportunity) => {
  try {
    // Create new PDF document (A4 size)
    const doc = new jsPDF();
    
    // Set up styling
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (2 * margin);
    let yPosition = margin;
    
    // Helper function to add text with word wrap
    const addText = (text, fontSize = 12, isBold = false, color = [0, 0, 0]) => {
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', isBold ? 'bold' : 'normal');
      doc.setTextColor(...color);
      
      const lines = doc.splitTextToSize(text, contentWidth);
      lines.forEach(line => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += fontSize * 0.5;
      });
      yPosition += 5;
    };
    
    // Helper function to add section header
    const addSectionHeader = (title) => {
      yPosition += 5;
      doc.setFillColor(240, 240, 240);
      doc.rect(margin, yPosition - 5, contentWidth, 10, 'F');
      addText(title, 14, true, [0, 0, 0]);
    };
    
    // Title
    addText(opportunity.title || 'Untitled Opportunity', 18, true, [0, 0, 128]);
    
    // Organization
    if (opportunity.org) {
      addText(opportunity.org, 14, false, [64, 64, 64]);
    }
    
    // Opportunity ID and Type
    const oppId = `OPP-${String(opportunity.id || '000').padStart(3, '0')}`;
    const oppType = (opportunity.type || 'OTHER').toUpperCase();
    addText(`${oppId} // ${oppType}`, 10, false, [128, 128, 128]);
    
    yPosition += 5;
    
    // Deadline and Urgency
    addSectionHeader('DEADLINE & URGENCY');
    if (opportunity.deadline_iso) {
      addText(`Deadline: ${opportunity.deadline_iso}`, 12);
    }
    addText(`Urgency: ${opportunity.urgency_badge || 'LOW'}`, 12);
    
    // Score Breakdown
    if (opportunity.score_breakdown) {
      addSectionHeader('SCORE BREAKDOWN');
      const sb = opportunity.score_breakdown;
      
      addText(`Total Score: ${sb.total}/105`, 12, true);
      yPosition += 3;
      
      if (sb.skill_alignment) {
        addText(`Skill Alignment: ${sb.skill_alignment.score}/55`, 11);
        addText(`  ${sb.skill_alignment.reason}`, 10, false, [64, 64, 64]);
      }
      
      if (sb.urgency) {
        addText(`Urgency: ${sb.urgency.score}/15`, 11);
        addText(`  ${sb.urgency.reason}`, 10, false, [64, 64, 64]);
        if (sb.urgency.date_confidence) {
          addText(`  Date Confidence: ${sb.urgency.date_confidence.toUpperCase()}`, 10, false, [64, 64, 64]);
        }
      }
      
      if (sb.type_match) {
        addText(`Type Match: ${sb.type_match.score}/15`, 11);
        addText(`  ${sb.type_match.reason}`, 10, false, [64, 64, 64]);
      }
      
      if (sb.location) {
        addText(`Location: ${sb.location.score}/10`, 11);
        addText(`  ${sb.location.reason}`, 10, false, [64, 64, 64]);
      }
      
      if (sb.financial_bonus) {
        addText(`Financial Bonus: ${sb.financial_bonus.score}/5`, 11);
        addText(`  ${sb.financial_bonus.reason}`, 10, false, [64, 64, 64]);
      }
      
      if (sb.completeness) {
        addText(`Completeness: ${sb.completeness.score}/5`, 11);
        addText(`  ${sb.completeness.reason}`, 10, false, [64, 64, 64]);
      }
    }
    
    // Action Checklist
    if (opportunity.checklist && opportunity.checklist.length > 0) {
      addSectionHeader('ACTION CHECKLIST');
      
      opportunity.checklist.forEach((item, index) => {
        const checkbox = item.done ? '☑' : '☐';
        const priorityLabel = item.priority === 1 ? '[HIGH]' : item.priority === 2 ? '[MED]' : '[LOW]';
        addText(`${checkbox} ${priorityLabel} ${item.task}`, 11, item.done);
      });
    }
    
    // Contact Information
    if (opportunity.link || opportunity.contact) {
      addSectionHeader('CONTACT & APPLICATION');
      
      if (opportunity.link) {
        addText(`Application Link: ${opportunity.link}`, 11);
      }
      
      if (opportunity.contact) {
        addText(`Contact: ${opportunity.contact}`, 11);
      }
    }
    
    // Footer
    yPosition = 280;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by Inbox Copilot on ${new Date().toLocaleString()}`, margin, yPosition);
    
    // Generate filename
    const sanitizedTitle = (opportunity.title || 'opportunity')
      .replace(/[^a-z0-9]/gi, '_')
      .toLowerCase()
      .substring(0, 50);
    const filename = `${sanitizedTitle}_${oppId}.pdf`;
    
    // Trigger download
    doc.save(filename);
    
    return { success: true, filename };
    
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
};

/**
 * Generate PDF for multiple opportunities
 * 
 * @param {Array} opportunities - Array of opportunity objects
 * @returns {void} - Triggers browser download
 */
export const generateBulkOpportunitiesPDF = (opportunities) => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPosition = margin;
    
    // Title page
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Opportunity Report', pageWidth / 2, 40, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Opportunities: ${opportunities.length}`, pageWidth / 2, 60, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 70, { align: 'center' });
    
    // Add each opportunity
    opportunities.forEach((opp, index) => {
      doc.addPage();
      yPosition = margin;
      
      // Use the single opportunity generator logic
      // (Simplified version for bulk export)
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(opp.title || 'Untitled', margin, yPosition);
      yPosition += 10;
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      if (opp.org) {
        doc.text(opp.org, margin, yPosition);
        yPosition += 8;
      }
      
      if (opp.score_breakdown) {
        doc.text(`Score: ${opp.score_breakdown.total}/105`, margin, yPosition);
        yPosition += 8;
      }
      
      if (opp.deadline_iso) {
        doc.text(`Deadline: ${opp.deadline_iso}`, margin, yPosition);
        yPosition += 8;
      }
    });
    
    // Save
    const filename = `opportunities_report_${Date.now()}.pdf`;
    doc.save(filename);
    
    return { success: true, filename, count: opportunities.length };
    
  } catch (error) {
    console.error('Bulk PDF generation error:', error);
    throw new Error(`Failed to generate bulk PDF: ${error.message}`);
  }
};
